# Generated by Django 4.2.28 on 2026-03-12 09:56

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0004_add_hardware_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_interval_minutes', models.IntegerField(default=15, help_text='Interval between power status checks (1-1440 minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('after_hours_cutoff', models.TimeField(default=datetime.time(20, 30), help_text="Time after which systems are considered 'after hours' (default 8:30 PM)")),
                ('notification_time', models.TimeField(default=datetime.time(17, 30), help_text='Time to send daily notification email (default 5:30 PM)')),
                ('after_hours_notification_time', models.TimeField(default=datetime.time(20, 45), help_text='Time to send after-hours notification (default 8:45 PM)')),
                ('ping_timeout_seconds', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('failure_threshold', models.IntegerField(default=3, help_text='Number of consecutive failures before marking offline', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name_plural': 'Monitoring Configurations',
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='SystemExemption',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='exemption', serialize=False, to='assets.asset')),
                ('reason', models.TextField(help_text='Justification for exemption')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Exemptions',
            },
        ),
        migrations.CreateModel(
            name='PowerStatus',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='power_status', serialize=False, to='assets.asset')),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('last_checked', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_status_change', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('online_since', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Power Statuses',
                'indexes': [models.Index(fields=['is_online', 'last_checked'], name='power_monit_is_onli_69a9c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PowerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_type', models.CharField(choices=[('status_change', 'Status Change'), ('shutdown_attempt', 'Shutdown Attempt'), ('shutdown_success', 'Shutdown Success'), ('shutdown_failure', 'Shutdown Failure'), ('exemption_added', 'Exemption Added'), ('exemption_removed', 'Exemption Removed'), ('notification_sent', 'Notification Sent')], db_index=True, max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_audit_logs', to='assets.asset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'action_type'], name='power_monit_timesta_81b757_idx'), models.Index(fields=['asset', '-timestamp'], name='power_monit_asset_i_c2f7a6_idx')],
            },
        ),
    ]
