# Generated by Django 4.2.28 on 2026-03-27 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_asset_health_status_asset_issues_description'),
        ('power_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_ranges', models.JSONField(default=list, help_text="List of IP ranges in CIDR notation (e.g., ['192.168.10.0/24'])")),
                ('concurrent_checks', models.IntegerField(default=10, help_text='Number of concurrent IP checks (1-50)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('timeout_seconds', models.IntegerField(default=2, help_text='Timeout for each IP check in seconds (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Scan Configurations',
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_ips', models.IntegerField(default=0)),
                ('online_count', models.IntegerField(default=0)),
                ('offline_count', models.IntegerField(default=0)),
                ('tracked_count', models.IntegerField(default=0)),
                ('discovered_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, protocol='IPv4')),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('detection_method', models.CharField(choices=[('icmp', 'ICMP Ping'), ('tcp_22', 'TCP Port 22'), ('tcp_80', 'TCP Port 80'), ('tcp_443', 'TCP Port 443'), ('none', 'Not Detected')], default='none', max_length=20)),
                ('is_tracked', models.BooleanField(db_index=True, default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_results', to='assets.asset')),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='power_monitoring.scanjob')),
            ],
            options={
                'ordering': ['ip_address'],
            },
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['status'], name='power_monit_status_857b38_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['-started_at'], name='power_monit_started_665dec_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['ip_address'], name='power_monit_ip_addr_7993b3_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['is_online'], name='power_monit_is_onli_95e708_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['is_tracked'], name='power_monit_is_trac_523614_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['checked_at'], name='power_monit_checked_d91daa_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['scan_job', 'is_online', 'is_tracked'], name='power_monit_scan_jo_efc731_idx'),
        ),
    ]
