# Generated by Django 4.2.28 on 2026-03-27 11:29

from django.db import migrations


def create_default_scan_config(apps, schema_editor):
    """Create default scan configuration with specified IP ranges."""
    ScanConfiguration = apps.get_model('power_monitoring', 'ScanConfiguration')
    
    # Create default configuration if it doesn't exist
    if not ScanConfiguration.objects.exists():
        ScanConfiguration.objects.create(
            ip_ranges=[
                '192.168.10.0/24',
                '192.168.11.0/24',
                '192.168.70.0/24',
                '192.168.50.0/24'
            ],
            concurrent_checks=10,
            timeout_seconds=2,
            is_active=True
        )


def reverse_default_scan_config(apps, schema_editor):
    """Remove default scan configuration."""
    ScanConfiguration = apps.get_model('power_monitoring', 'ScanConfiguration')
    ScanConfiguration.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('power_monitoring', '0002_scanconfiguration_scanjob_scanresult_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_scan_config, reverse_default_scan_config),
    ]
