# Generated by Django 4.2.28 on 2026-02-11 06:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(db_index=True, help_text='Format: BIDC + number', max_length=50, unique=True)),
                ('system_type', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('All-in-One PC', 'All-in-One PC')], max_length=20)),
                ('particulars', models.TextField(blank=True, help_text='Detailed information about the asset', null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('freed', 'Freed'), ('scrapped', 'Scrapped')], db_index=True, default='active', max_length=20)),
                ('warranty_expiration', models.DateField(blank=True, db_index=True, null=True)),
                ('freed_date', models.DateTimeField(blank=True, null=True)),
                ('scrapped_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='IPRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_pattern', models.CharField(help_text='e.g., 192.168.10.x', max_length=20, unique=True)),
                ('network_prefix', models.CharField(help_text='e.g., 192.168.10', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['range_pattern'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(protocol='IPv4', unique=True, validators=[django.core.validators.validate_ipv4_address])),
                ('is_assigned', models.BooleanField(db_index=True, default=False)),
                ('assigned_to_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ips', to='assets.asset')),
                ('ip_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='assets.iprange')),
            ],
            options={
                'verbose_name_plural': 'IP Addresses',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='asset_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.asset')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset', to='assets.ipaddress'),
        ),
        migrations.AddField(
            model_name='asset',
            name='operating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.operatingsystem'),
        ),
        migrations.AddField(
            model_name='asset',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.team'),
        ),
    ]
