# Generated by Django 4.2.28 on 2026-03-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_teams', to='assets.team'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['parent', 'name'], name='assets_team_parent__e2e693_idx'),
        ),
    ]
