# Generated by Django 4.2.28 on 2026-03-09 08:20

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def populate_teams(apps, schema_editor):
    """Populate the team hierarchy with pre-defined teams."""
    Team = apps.get_model('assets', 'Team')
    
    logger.info("Starting team hierarchy population")
    
    # Create or update parent teams
    parent_teams = {}
    parent_team_names = [
        'Marketing',
        'Developers',
        'Data Center Team',
        'Accounts Team',
        'Iboss Support Team'
    ]
    
    for name in parent_team_names:
        team, created = Team.objects.get_or_create(name=name)
        parent_teams[name] = team
        action = "Created" if created else "Found existing"
        logger.info(f"{action} parent team: {name}")
    
    # Create Not Applicable option
    not_applicable, created = Team.objects.get_or_create(name='Not Applicable')
    action = "Created" if created else "Found existing"
    logger.info(f"{action} special team: Not Applicable")
    
    # Create sub-teams under Developers
    developers_parent = parent_teams['Developers']
    sub_team_names = [
        'Bethovans Team', 'QC Team', 'App Team', 'Hotel Team',
        'Suma Team', 'Iboss Team', 'Robin Team', 'Jojo Team',
        'Sandeep Team', 'Dulfi Team', 'Design Team', 'Justine MJ Team',
        'Jinson Team', 'Jerly Team', 'DBA Team', 'JOJO Team',
        'BA Team', 'Adhun Team', 'Aymen Team'
    ]
    
    for name in sub_team_names:
        team, created = Team.objects.get_or_create(name=name)
        if created or not team.parent:
            team.parent = developers_parent
            team.save()
            action = "Created" if created else "Updated"
            logger.info(f"{action} sub-team under Developers: {name}")
    
    logger.info("Team hierarchy population completed")


def reverse_populate_teams(apps, schema_editor):
    """Clear parent relationships but preserve teams."""
    Team = apps.get_model('assets', 'Team')
    
    logger.info("Reversing team hierarchy population")
    Team.objects.all().update(parent=None)
    logger.info("Cleared all parent relationships")


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_add_team_hierarchy'),
    ]

    operations = [
        migrations.RunPython(populate_teams, reverse_populate_teams),
    ]
