# Generated by Django 4.2.28 on 2026-03-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_populate_team_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hardware_serial_number',
            field=models.CharField(blank=True, help_text='Hardware serial number (required for Laptop and All-in-One PC)', max_length=100, null=True),
        ),
    ]
