# Generated by Django 4.2.28 on 2026-03-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_add_hardware_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer or brand of the asset', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='scrapping_reason',
            field=models.TextField(blank=True, help_text='Explanation for why the asset was scrapped', null=True),
        ),
    ]
