# Generated by Django 4.2.28 on 2026-03-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_manufacturer_and_scrapping_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='freed_date',
            field=models.DateTimeField(blank=True, help_text='Date when IP was released from an asset', null=True),
        ),
    ]
