# Generated by Django 4.2.28 on 2026-03-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_add_freed_date_to_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manual_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Manually entered IP address (not tracked in IP management)', null=True, protocol='IPv4'),
        ),
    ]
