# Generated by Django 4.2.28 on 2026-03-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_add_manual_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='health_status',
            field=models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('defective', 'Defective')], help_text='Health status for freed systems', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='issues_description',
            field=models.TextField(blank=True, help_text='Description of issues for defective freed systems', null=True),
        ),
    ]
