# Generated by Django 4.2.28 on 2026-04-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_asset_health_status_asset_issues_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Camera', 'Camera'), ('Printer', 'Printer'), ('Punching Machine', 'Punching Machine'), ('Mobile', 'Mobile'), ('Other', 'Other')], max_length=50)),
                ('device_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='network_device', to='assets.ipaddress')),
            ],
            options={
                'ordering': ['device_name'],
                'indexes': [models.Index(fields=['device_type'], name='assets_netw_device__3c1958_idx'), models.Index(fields=['device_name'], name='assets_netw_device__eff1dd_idx')],
            },
        ),
    ]
